# Conduit
# Using 3xpo/alpine-conduit-base (unofficial, CI built image) and 3xpo/matrix-clients
#   For non-local use: First replace `http://localhost` with `https://localhost`, then replace `localhost` with your domain

services:
  matrix-homeserver:
    image: docker.io/3xpo/alpine-conduit-base:latest
    container_name: matrix-homeserver
    restart: unless-stopped
    networks:
      - matrix
    volumes:
      - ./matrix-data/db:/var/lib/matrix-conduit:rw
    environment:
      CONDUIT_SERVER_NAME: localhost # <- Set this to your homeserver's domain!!
      CONDUIT_DATABASE_PATH: /var/lib/matrix-conduit
      CONDUIT_DATABASE_BACKEND: rocksdb
      CONDUIT_PORT: 80
      CONDUIT_MAX_REQUEST_SIZE: 20000000 # in bytes, ~20 MB
      CONDUIT_ALLOW_REGISTRATION: 'true'
      CONDUIT_ALLOW_FEDERATION: 'true'
      CONDUIT_ALLOW_CHECK_FOR_UPDATES: 'true'
      CONDUIT_TRUSTED_SERVERS: '["matrix.org"]'
      CONDUIT_MAX_CONCURRENT_REQUESTS: 100
    entrypoint: sleep 1000000
  matrix-clients:
    image: docker.io/3xpo/matrix-clients:latest
    container_name: matrix-clients
    restart: unless-stopped
    networks:
      - matrix
    volumes:
      - ./matrix-data/caddy/client:/var/lib/caddy/:rw
    environment:
      LISTEN_ON: ":80"
      ALLOW_FRAMING: "false"
      DISABLE_XSS_PROTECTION: "false"
      DISABLE_NOSNIFF: "false"
      FEDERATION_TARGET: "localhost" # <- Set this to your homeserver's domain!!
      HOMESERVER_BASE_URL: "localhost" # <- Set this to your homeserver's domain!!
      # PROXY_MATRIX_TRAFFIC_TO: "http://matrix-homeserver" # You would use this if you wanted both the frontend and backend on the same domain, and wanted to directly expose this container
      REDIRECT_MATRIX_TRAFFIC_TO: "http://localhost"
      USE_PERMANENT_MATRIX_REDIRECT: "false"
      DEFAULT_CLIENT_HOMESERVER: "localhost"
  matrix-router:
    image: docker.io/3xpo/matrix-router:latest
    container_name: matrix-router
    restart: unless-stopped
    ports:
      - 1180:80
      - 1443:443
    networks:
      - matrix
    volumes:
      - ./matrix-data/caddy/router:/var/lib/caddy/:rw
    environment:
      CLIENT_LISTEN_ON: "http://frontend.localhost"
      SERVER_LISTEN_ON: "http://localhost"
      CLIENT_LIVES_AT: "http://matrix-clients"
      SERVER_LIVES_AT: "http://matrix-homeserver"
    depends_on:
      - matrix-homeserver
      - matrix-clients

networks:
  matrix:
