#!/bin/bash
set -eax
if ! [[ -f ~/.config/qBittorrent/qBittorrent.conf ]]; then
  sudo mkdir -p ~/.config/qBittorrent;
  sudo mv ~/.qb-default-config/* ~/.config/qBittorrent/
fi;
sudo chown -R qb "${HOME}" "${HOME}/.config" "${HOME}/.config/qBittorrent"
rm -rf ~/.qb-default-config/
sudo rm /etc/sudoers.d/qb
exec "$@"
