#!/usr/bin/env bash

if [[ -f "$(dirname $0)/../../contrib/config/sh" ]]; then
  source "$(dirname $0)/../../contrib/config/sh"
fi

set -ea

# Sets the version to 1.0.YYYYMMDD-hh-mm in the package.json file
"$JQ" '.version="1.0.'$(date +%Y%m%d-%H-%M)'"' package.json > package.json.tmp
mv package.json.tmp package.json
echo "Version set to $("$JQ" -r .version package.json)"
