#!/usr/bin/env bash

set -ea
nx exec -- sed -i "s/#CI:INSERT_VERSION_LABEL/LABEL org.opencontainers.image.version=\"$(jq -r .version package.json)\"/g" Dockerfile
nx exec -- sed -i "s/#CI:INSERT_REVISION_LABEL/LABEL org.opencontainers.image.version=\"$(git rev-parse HEAD)\"/g" Dockerfile
nx exec -- sed -i "s/#CI:INSERT_CREATION_LABEL/LABEL org.opencontainers.image.version=\"$(date +%Y-%m-%dT%H:%M:%S)\"/g" Dockerfile
