ARG ALPINE_RELEASE_CHANNEL="latest"
FROM docker.io/alpine:${ALPINE_RELEASE_CHANNEL} AS base

RUN apk --no-cache update
RUN apk --no-cache upgrade
RUN apk --no-cache add nano shadow sudo
RUN useradd lain
RUN mkhomedir_helper lain || true
COPY ./files/lain-sudoers /etc/sudoers.d/lain

FROM scratch

LABEL org.opencontainers.image.title="Expo's Alpine Base Image"
LABEL org.opencontainers.image.description="Preset Containerd image of Alpine Linux Stable."
LABEL org.opencontainers.image.authors="Expo <expo.containers@breadhub.cc>"
LABEL org.opencontainers.image.url="https://codeberg.org/Expo/containers"
LABEL org.opencontainers.image.documentation="https://codeberg.org/Expo/containers/src/branch/master/containers/alpine/base/README.md"
LABEL org.opencontainers.image.source="https://codeberg.org/Expo/containers"
LABEL org.opencontainers.image.licenses="MIT"
#CI:INSERT_VERSION_LABEL
#CI:INSERT_REVISION_LABEL
#CI:INSERT_CREATION_LABEL

COPY --from=base / /
RUN chown -R lain:lain /home/lain
USER lain
ENV HOME="/home/lain"
ENV USER="lain"
WORKDIR /home/lain
CMD [ "sh" ]
