FROM docker.io/3xpo/base

LABEL org.opencontainers.image.title="Expo's Arch Linux Dart Base Image"
LABEL org.opencontainers.image.description="Preset Containerd image of Arch Linux with a general decent baseline flutter build environment."
LABEL org.opencontainers.image.documentation="https://codeberg.org/Expo/containers/src/branch/master/containers/ci/base-flutter/README.md"
LABEL org.opencontainers.image.licenses="GPL-3.0-or-later"

RUN sudo pacman -S --noconfirm --needed dart git curl wget jq yq unzip which
ENV PATH="${PATH}:/opt/flutter/bin"
RUN curl -fLo /tmp/flutter.tar.xz 'https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.22.2-stable.tar.xz' && \
  sudo tar -xf /tmp/flutter.tar.xz -C /opt/ && \
  rm /tmp/flutter.tar.xz && \
  sudo git config --global --add safe.directory /opt/flutter && \
  sudo flutter --disable-analytics && \
  flutter --disable-analytics && \
  sudo flutter --disable-analytics && \
  flutter --disable-analytics && \
  sudo flutter upgrade
