FROM docker.io/3xpo/base-flutter-bootstrap:latest as flutter
FROM docker.io/3xpo/base:latest

LABEL org.opencontainers.image.title="Expo's Arch Linux Dart Base Image"
LABEL org.opencontainers.image.description="Preset Containerd image of Arch Linux with a general decent baseline flutter build environment."
LABEL org.opencontainers.image.documentation="https://codeberg.org/Expo/containers/src/branch/master/containers/ci/base-flutter/README.md"
LABEL org.opencontainers.image.licenses="GPL-3.0-or-later"

RUN sudo pacman -S --noconfirm --needed dart git curl wget jq yq unzip which
ENV FLUTTER_INSTALL_DIR="/usr/bin/flutter"
ENV PATH="${PATH}:${FLUTTER_INSTALL_DIR}/bin"
COPY --from=flutter --chown=astolfo:astolfo --chmod=755 "${FLUTTER_INSTALL_DIR}" "${FLUTTER_INSTALL_DIR}"
RUN git config --global --add safe.directory "${FLUTTER_INSTALL_DIR}" && \
  flutter --disable-analytics && \
  sudo flutter --disable-analytics && \
  flutter upgrade
