FROM docker.io/3xpo/base AS cinny

# Prepare Env
ARG BUILD_TAG="latest"
WORKDIR "${HOME}"
RUN sudo pacman -S --noconfirm --needed jq

# Clone Cinny
RUN git clone "https://github.com/cinnyapp/cinny.git" "${HOME}/cinny-web" --recursive
WORKDIR "${HOME}/cinny-web"

# Select the right tag
RUN sh -c "if [[ '${BUILD_TAG}' == 'latest' ]]; then GIT_TAG=\$(git tag | sort -V | grep -v rc | grep -v alpha | grep -v beta | tail -n 1); echo \"Using version \$GIT_TAG\"; git reset --hard \$GIT_TAG; elif [[ '${BUILD_TAG}' == 'rc' ]]; then GIT_TAG=\$(git describe --tags --abbrev=0); echo \"Using version \$GIT_TAG\"; git reset --hard \$GIT_TAG; fi"

# Install Deps
RUN npm i --no-audit --no-fund && npm audit fix --force

# Make the build config not use a base of /
RUN sed "s|base: '/',|base: './',|g" -i build.config.ts

# Build
RUN npm run build

# Move to /cinny-web
RUN jq '.isDefaultConfig=true' "${HOME}/cinny-web/dist/config.json" > /tmp/conf.json && jq '.hashRouter.enabled=true' /tmp/conf.json > "${HOME}/cinny-web/dist/config.json" && rm /tmp/conf.json
RUN sudo mv "${HOME}/cinny-web/dist" /cinny-web

FROM scratch
COPY --from=cinny /cinny-web/ /
