FROM docker.io/3xpo/alpine-base

LABEL org.opencontainers.image.title="Expo's Prometheus Image"
LABEL org.opencontainers.image.description="Preset Containerd image of Alpine Linux with prometheus preinstalled."
LABEL org.opencontainers.image.documentation="https://codeberg.org/Expo/containers/src/branch/master/containers/alpine/prometheus/README.md"

ENV PROMETHEUS_INSTALL="${HOME}/Prometheus"
USER root
RUN apk --no-cache add luajit git neovim nano
USER lain
RUN git clone "https://github.com/prometheus-lua/Prometheus.git" "${PROMETHEUS_INSTALL}"
COPY files/prometheus /bin/prometheus
USER root
RUN chmod +x /bin/prometheus && mkdir -p /scripts
USER lain
VOLUME [ "/scripts" ]
CMD ["/bin/prometheus","--preset","Medium","/scripts/script.lua"]
