FROM docker.io/3xpo/alpine-base

LABEL org.opencontainers.image.title="Expo's Prometheus Image"
LABEL org.opencontainers.image.description="Preset Containerd image of Alpine Linux with prometheus preinstalled."
LABEL org.opencontainers.image.documentation="https://codeberg.org/Expo/containers/src/branch/master/containers/alpine/prometheus/README.md"

ENV PROMETHEUS_INSTALL="${HOME}/Prometheus"
USER root
RUN ([[ "$(arch)" != "riscv64" ]] && apk --no-cache add luajit || apk --no-cache add lua5.1) && apk --no-cache add git nano
RUN git clone "https://github.com/prometheus-lua/Prometheus.git" "${PROMETHEUS_INSTALL}"
COPY files/prometheus /bin/prometheus
RUN chmod +x /bin/prometheus && mkdir -p /scripts && chown -R lain /home/lain "${PROMETHEUS_INSTALL}"
USER lain
VOLUME [ "/scripts" ]
CMD ["/bin/prometheus","--preset","Medium","/scripts/script.lua"]
