FROM scratch as blank

# the outputs are all built on amd64, even though they work multiarch, due to flutter only being on amd64 - hence we specify a FROM of specifically amd64 here
# and have this image output many diff archs, as it just copies from those
ARG BUILD_TAG="latest"
FROM --platform=amd64 docker.io/3xpo/cinny-web-files:${BUILD_TAG} AS cinny
ARG BUILD_TAG="latest"
FROM --platform=amd64 docker.io/3xpo/element-web-files:${BUILD_TAG} AS element
ARG BUILD_TAG="latest"
FROM --platform=amd64 docker.io/3xpo/fluffychat-web-files:${BUILD_TAG} AS fluffychat

FROM blank
COPY ./files/ /
COPY --from=cinny / /cinny
COPY --from=element / /element
COPY --from=fluffychat / /fluffychat
