FROM docker.io/3xpo/base-flutter AS fluffychat

# Prepare Env
ARG BUILD_TAG="latest"
WORKDIR "${HOME}"
RUN sudo pacman -S --needed --noconfirm libolm

# Clone Flufflychat
RUN git clone "https://github.com/krille-chan/fluffychat.git" "${HOME}/fluffychat" --recursive
WORKDIR "${HOME}/fluffychat"

# Select the right tag
RUN sh -c "if [[ '${BUILD_TAG}' == 'latest' ]]; then GIT_TAG=\$(git tag | sort -V | grep -v rc | grep -v alpha | grep -v beta | tail -n 1); echo \"Using version \$GIT_TAG\"; git reset --hard \$GIT_TAG; elif [[ '${BUILD_TAG}' == 'rc' ]]; then GIT_TAG=\$(git describe --tags --abbrev=0); echo \"Using version \$GIT_TAG\"; git reset --hard \$GIT_TAG; fi; echo -n \"\$GIT_TAG\""

# Build
RUN flutter build web --release

# Move to /fluffychat-web
RUN sudo mv "${HOME}/fluffychat/build/web" /fluffychat-web

FROM scratch
COPY --from=fluffychat /fluffychat-web/ /
