ARG ALPINE_RELEASE_CHANNEL="latest"
FROM docker.io/3xpo/alpine-base:${ALPINE_RELEASE_CHANNEL}

USER root
RUN apk --no-cache add qbittorrent-nox shadow sudo bash python3

COPY ./files/qb-entrypoint "/usr/bin/qb-entrypoint"

# entrypoint removes this:
COPY ./files/temp-sudoers-qb "/etc/sudoers.d/qb"

ENV HOME="/home/qb"
RUN useradd qb
RUN mkdir -p "${HOME}" && chown -R qb "${HOME}" && chmod +x /usr/bin/qb-entrypoint
USER qb
ENV DOWNLOADS="${HOME}/Downloads"
WORKDIR "${HOME}"
RUN mkdir -p "${DOWNLOADS}" "${HOME}/.qb-default-config"
COPY ./files/qBittorrent.conf "${HOME}/.qb-default-config/qBittorrent.conf"
RUN rm -rf "${HOME}/.config/qBittorrent"
EXPOSE 8080
VOLUME [ "${HOME}/.config/qBittorrent", "${DOWNLOADS}", "${HOME}/.local/share/qBittorrent" ]

ENTRYPOINT [ "/usr/bin/qb-entrypoint" ]
CMD [ "/usr/bin/qbittorrent-nox" ]
