FROM docker.io/3xpo/base AS element

# Prepare Env
ARG BUILD_TAG="latest"
WORKDIR "${HOME}"
RUN pnpm i -g yarn

# Clone Element
RUN git clone "https://github.com/element-hq/element-web.git" "${HOME}/element-web" --recursive
WORKDIR "${HOME}/element-web"

# Select the right tag
RUN sh -c "if [[ '${BUILD_TAG}' == 'latest' ]]; then GIT_TAG=\$(git tag | sort -V | grep -v rc | grep -v alpha | grep -v beta | tail -n 1); echo \"Using version \$GIT_TAG\"; git reset --hard \$GIT_TAG; elif [[ '${BUILD_TAG}' == 'rc' ]]; then GIT_TAG=\$(git describe --tags --abbrev=0); echo \"Using version \$GIT_TAG\"; git reset --hard \$GIT_TAG; fi"

# Setup configs
COPY ./files/config.json "${HOME}/element-web/config.json"
COPY ./files/env "${HOME}/element-web/.env"

# Install Deps
RUN yarn

# Update caniuselite db
RUN yarn dlx update-browserslist-db@latest

# TODO: remove this, upstream is incompetent
RUN yarn add temporal-polyfill

# Build
RUN yarn build

# Move to /element-web
RUN sudo mv "${HOME}/element-web/webapp" /element-web
COPY ./files/config.json "/element-web/config.json"

FROM scratch
COPY --from=element /element-web/ /
