name: Publish

on:
  push:
    branches:
      - master
  schedule:
    - cron: '47 */2 * * *'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies 1
        run: |
          sudo apt install build-essential libssl-dev git make bash jq -y

      - name: Trixie-ify
        run: |
          (curl -fL 'https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x0E98404D386FA1D9' -o /tmp/0x0E98404D386FA1D9.asc && sudo mv /tmp/0x0E98404D386FA1D9.asc /etc/apt/trusted.gpg.d/) &
          (curl -fL 'https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x6ED0E7B82643E131' -o /tmp/0x6ED0E7B82643E131.asc && sudo mv /tmp/0x6ED0E7B82643E131.asc /etc/apt/trusted.gpg.d/) &
          sudo sh -c "echo 'deb http://ftp.debian.org/debian trixie main' >> /etc/apt/sources.list"
          sudo sh -c "echo 'deb-src http://ftp.debian.org/debian trixie main' >> /etc/apt/sources.list"
          sudo sh -c "echo 'deb http://ftp.ch.debian.org/debian trixie main' >> /etc/apt/sources.list"
          sudo sh -c "echo 'deb-src http://ftp.ch.debian.org/debian trixie main' >> /etc/apt/sources.list"
          sudo sh -c "echo 'deb http://ftp.de.debian.org/debian trixie main' >> /etc/apt/sources.list"
          sudo sh -c "echo 'deb-src http://ftp.de.debian.org/debian trixie main' >> /etc/apt/sources.list"
          sudo sh -c "echo 'deb http://ftp.ca.debian.org/debian trixie main' >> /etc/apt/sources.list"
          sudo sh -c "echo 'deb-src http://ftp.ca.debian.org/debian trixie main' >> /etc/apt/sources.list"
          sudo apt update
          wait

      - name: Update System
        run: sudo apt upgrade -y

      - name: Run multiarch/qemu-user-static
        run: sudo podman run --rm --privileged multiarch/qemu-user-static --reset -p yes

      - name: Install Dependencies 2
        run: |
          sudo apt install podman/trixie buildah/trixie qemu-system/trixie qemu-user/trixie qemu-user-static/trixie binfmt-support/trixie -y

      - name: Enable Binfmt Support
        run: |
          sudo /usr/sbin/update-binfmts --enable

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 'latest'

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Bootstrap
        run: ./bootstrap

      - name: Configure
        run: |
          ./configure --arch=any

      - name: Update Version Number
        run: ./img-tools/ci/set-version

      - name: Update CI-generated Metadata
        run: ./img-tools/ci/update-ci-instructions

      - name: Pull arch base
        run: podman pull docker.io/3xpo/base:latest

      - name: Pull alpine base
        run: podman pull docker.io/3xpo/alpine-base:latest

      - name: Pull alpine base, edge
        run: podman pull docker.io/3xpo/alpine-base:edge

      - name: Pull arch base-flutter
        run: podman pull docker.io/3xpo/base-flutter:latest

      - name: Build OCI images
        run: |
          WRITE_TO_PUSH_SCRIPT=/tmp/deploy.sh pnpm build --output-style stream

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Publish Images
        run: |
          chmod +x /tmp/deploy.sh
          /tmp/deploy.sh
          rm -rf /tmp/deploy.sh

      - name: Cleanup
        run: |
          podman system prune -af
          podman system prune -af --external --volumes
          podman image prune -af --external
