name: Publish

on:
  push:
    branches:
      - master
  schedule:
    - cron: '47 */2 * * *'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Install System Dependencies
        run: |
          sudo apt install build-essential libssl-dev git make bash jq -y

      - name: Install Build Dependencies
        run: |
          sudo apt install podman buildah qemu-system qemu-user qemu-user-static binfmt-support -y

      - name: Run multiarch/qemu-user-static
        run: sudo podman run --rm --privileged multiarch/qemu-user-static --reset -p yes

      - name: Enable Binfmt Support
        run: |
          sudo /usr/sbin/update-binfmts --enable

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 'latest'

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Bootstrap
        run: ./bootstrap

      - name: Configure
        run: |
          ./configure --arch=any

      - name: Update Version Number
        run: ./img-tools/ci/set-version

      - name: Update CI-generated Metadata
        run: ./img-tools/ci/update-ci-instructions

      - name: Pull arch base
        run: podman pull docker.io/3xpo/base:latest

      - name: Pull alpine base
        run: podman pull docker.io/3xpo/alpine-base:latest

      - name: Pull alpine base, edge
        run: podman pull docker.io/3xpo/alpine-base:edge

      - name: Pull arch base-flutter
        run: podman pull docker.io/3xpo/base-flutter:latest

      - name: Build OCI images
        run: |
          WRITE_TO_PUSH_SCRIPT=/tmp/deploy.sh pnpm build --output-style stream

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Publish Images
        run: |
          chmod +x /tmp/deploy.sh
          /tmp/deploy.sh
          rm -rf /tmp/deploy.sh

      - name: Cleanup
        run: |
          podman system prune -af
          podman system prune -af --external --volumes
          podman image prune -af --external
